# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mQKjMylEI4hatSG312Oa9bWcTJ2Kqj58
"""

import pandas as pd

df = pd.read_csv('dataset_churn_clientes.csv')
df.head()

df.info()
df['churn'].value_counts(normalize=True)

import matplotlib.pyplot as plt

df.groupby('churn')[['frequencia_compra_mensal', 'dias_desde_ultima_compra',
                       'reclamacoes_ultimo_ano', 'desconto_medio_solicitado_pct']].mean()

df_numerico = df.drop(columns=['cliente_id', 'canal_preferido', 'categoria_principal'])
df_numerico.corr()['churn'].sort_values(ascending=False)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

df_modelo = df.drop(columns=['cliente_id']).copy()

le = LabelEncoder()
df_modelo['canal_preferido'] = le.fit_transform(df_modelo['canal_preferido'])
df_modelo['categoria_principal'] = le.fit_transform(df_modelo['categoria_principal'])

X = df_modelo.drop(columns=['churn'])
y = df_modelo['churn']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

modelo = LogisticRegression(max_iter=1000, class_weight='balanced')
modelo.fit(X_train_scaled, y_train)

from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

y_pred = modelo.predict(X_test_scaled)

print(classification_report(y_test, y_pred))

ConfusionMatrixDisplay.from_predictions(y_test, y_pred, display_labels=['Não churn', 'Churn'])
plt.show()

import pandas as pd

coeficientes = pd.DataFrame({
    'variavel': X.columns,
    'coeficiente': modelo.coef_[0]
}).sort_values('coeficiente', ascending=False)

coeficientes

import seaborn as sns

fig, axes = plt.subplots(1, 3, figsize=(16, 4))

sns.boxplot(data=df, x='churn', y='dias_desde_ultima_compra', ax=axes[0])
axes[0].set_title('Dias desde última compra')

sns.boxplot(data=df, x='churn', y='frequencia_compra_mensal', ax=axes[1])
axes[1].set_title('Frequência de compra mensal')

sns.barplot(data=df, x='canal_preferido', y='churn', ax=axes[2])
axes[2].set_title('Taxa de churn por canal')

plt.tight_layout()
plt.savefig('eda_distribuicoes.png', dpi=150, bbox_inches='tight')
plt.show()

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=200, class_weight='balanced', random_state=42)
rf.fit(X_train_scaled, y_train)

y_pred_rf = rf.predict(X_test_scaled)
print(classification_report(y_test, y_pred_rf))

importancias = pd.DataFrame({
    'variavel': X.columns,
    'importancia': rf.feature_importances_
}).sort_values('importancia', ascending=True)

plt.figure(figsize=(8, 5))
plt.barh(importancias['variavel'], importancias['importancia'])
plt.title('Importância das variáveis - Random Forest')
plt.tight_layout()
plt.savefig('importancia_variaveis.png', dpi=150, bbox_inches='tight')
plt.show()

from sklearn.metrics import RocCurveDisplay

fig, ax = plt.subplots(figsize=(6, 6))
RocCurveDisplay.from_estimator(modelo, X_test_scaled, y_test, ax=ax, name='Regressão Logística')
RocCurveDisplay.from_estimator(rf, X_test_scaled, y_test, ax=ax, name='Random Forest')
ax.plot([0, 1], [0, 1], linestyle='--', color='gray', label='Aleatório')
ax.legend()
plt.title('Curva ROC - comparação de modelos')
plt.savefig('curva_roc.png', dpi=150, bbox_inches='tight')
plt.show()